set(CMAKE_SYSTEM_NAME foliOS)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TARGET_NAME ${CMAKE_SYSTEM_PROCESSOR}-strata-folios)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TOOLCHAIN_PREFIX "${TARGET_NAME}-")

set(CMAKE_C_COMPILER_TARGET     ${TARGET_NAME})
find_program(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}gcc" ENV PATH)

set(CMAKE_CXX_COMPILER_TARGET   ${TARGET_NAME})
find_program(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}g++" ENV PATH)

set(CMAKE_ASM_COMPILER_TARGET   ${TARGET_NAME})
find_program(CMAKE_ASM_COMPILER "${TOOLCHAIN_PREFIX}as" ENV PATH)

set(CMAKE_LINKER "${CMAKE_C_COMPILER}")

set(_BINUTILS_LIST LD;AR;NM;OBJCOPY;OBJDUMP;RANLIB;READELF;STRIP)

foreach(TOOL_NAME IN LISTS _BINUTILS_LIST)
    string(TOLOWER ${TOOL_NAME} _TOOL_BIN_NAME)
    find_program(CMAKE_${TOOL_NAME}
        "${TARGET_NAME}-${_TOOL_BIN_NAME}"
        HINTS "${CMAKE_FIND_ROOT_PATH}/bin" ENV PATH
        REQUIRED
        NO_CMAKE_FIND_ROOT_PATH)
    unset(_TOOL_BIN_NAME)
endforeach()

unset(_BINUTILS_LIST)
